composite version

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -1,8 +1,47 @@
+# action.yml
 name: 'SPC OIDC Login'
 description: 'GitHub Actions OIDC login for SPC'
 runs:
-  using: 'bash'
-  main: 'entrypoint.sh'
+  using: 'composite'
+  steps:
+    - name: Configure SPC Credentials
+      shell: bash
+      run: |
+
+        export AWS_RESPONSE_CHECKSUM_VALIDATION=${AWS_RESPONSE_CHECKSUM_VALIDATION:-when_required}
+        export AWS_REQUEST_CHECKSUM_CALCULATION=${AWS_REQUEST_CHECKSUM_CALCULATION:-when_required}
+
+
+        ID_TOKEN=$(curl -sSL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
+          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.samsungspc.com" | jq -r '.value')
+
+        if [ -z "$ID_TOKEN" ] || [ "$ID_TOKEN" == "null" ]; then
+          echo "Error: OIDC token could not be fetched." >&2
+          exit 1
+        fi
+
+
+        echo "===== OIDC Token Claims ====="
+        echo "$ID_TOKEN" | cut -d "." -f2 | base64 -d | jq .
+        echo "============================="
+
+
+        RESPONSE=$(aws sts assume-role-with-web-identity \
+          --role-arn "${{ inputs.role_arn }}" \
+          --role-session-name "GitHubActionsSession" \
+          --web-identity-token "${ID_TOKEN}" \
+          --endpoint-url "${{ inputs.sts_endpoint }}" \
+          --output json)
+
+        ACCESS_KEY=$(echo $RESPONSE | jq -r '.Credentials.AccessKeyId')
+        SECRET_KEY=$(echo $RESPONSE | jq -r '.Credentials.SecretAccessKey')
+        SESSION_TOKEN=$(echo $RESPONSE | jq -r '.Credentials.SessionToken')
+
+
+        echo "AWS_ACCESS_KEY_ID=$ACCESS_KEY" >> $GITHUB_ENV
+        echo "AWS_SECRET_ACCESS_KEY=$SECRET_KEY" >> $GITHUB_ENV
+        echo "AWS_SESSION_TOKEN=$SESSION_TOKEN" >> $GITHUB_ENV
+
 inputs:
   role_arn:
     description: 'SPC IAM Role ARN'
